server.port=8081
spring.application.name=eshop
# H2 database to test in localhosst8080/urldown
spring.datasource.url=jdbc:h2:mem:eshopdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

security.jwt.secret=mysecretkeymysecretkeymysecretkey123
security.jwt.expiration-ms=3600000
